### ISSUE TITLE
window_len == 1 in generation phase

### ISSUE THREAD

**Issue by cyLi-Tiger** [mutonix/pyramidinfer#1]
Thanks for the great work!

[here](https://github.com/mutonix/pyramidinfer/blob/a991c7fa57a2b9b33e8db42a1b94cfd8c27cab23/models/modeling_llama_pyramidinfer.py#L819), the `window_len` == 1, is it expected?

Besides, why evict tokens from `-(1 + gen_recent_length + exceed_length_to_compress):-(1 + gen_recent_length)` but not `-(gen_recent_length + exceed_length_to_compress):-(gen_recent_length)`? What's the point of 1 here?

**Comment by mutonix** [comment]
Many thanks for your meticulous inspection. It is a bug we missed during the code reorganization and we fixed it in the latest commit in [here](https://github.com/mutonix/pyramidinfer/blob/b16f4ca9c24ae28c6c0c788108546f0a3bd4f4ed/models/modeling_llama_pyramidinfer.py#L812).

The 1 here added to `recent_length` is a legacy behavior from earlier code, which has no influence and can be deleted. Keeping it will only result in a longer window length increased by 1.
